INSERT INTO test_categories VALUES (0, 'Автомобили', null);
INSERT INTO test_categories VALUES (1, 'Легковые', 0);
INSERT INTO test_categories VALUES (2, 'Грузовые', 0);
INSERT INTO test_categories VALUES (3, 'Оценить Авто', null);
INSERT INTO test_categories VALUES (4, 'Каталог Авто', null);
INSERT INTO test_categories VALUES (5, 'Мотоциклы', null);
INSERT INTO test_categories VALUES (6, 'Эндуро', 5);
INSERT INTO test_categories VALUES (7, 'Квадро', 5);
INSERT INTO test_categories VALUES (8, '400 кубов', 6);
INSERT INTO test_categories VALUES (9, '800 кубов', 6);
INSERT INTO test_categories VALUES (10, 'Грузовики', null);
INSERT INTO test_categories VALUES (11, 'Промышленные', 10);
INSERT INTO test_categories VALUES (12, 'Фуры', 10);
INSERT INTO test_categories VALUES (13, 'MAN', 12);
INSERT INTO test_categories VALUES (14, 'VOLVO', 12);
INSERT INTO test_categories VALUES (15, 'Водный транспорт', null);
INSERT INTO test_categories VALUES (16, 'Лодки', 15);
INSERT INTO test_categories VALUES (17, 'Утята', 15);
INSERT INTO test_categories VALUES (18, 'Спасательные жилеты', 15);
INSERT INTO test_categories VALUES (19, 'Запчасти и аксесуары', null);
INSERT INTO test_categories VALUES (20, 'Запчасти', 19);
INSERT INTO test_categories VALUES (21, 'Для автомобилей', 20);
INSERT INTO test_categories VALUES (22, 'Для мототехники', 20);
INSERT INTO test_categories VALUES (23, 'Для грузовиков', 20);
INSERT INTO test_categories VALUES (24, 'Для водного транспорта', 20);
INSERT INTO test_categories VALUES (25, 'Шины диски', 19);
INSERT INTO test_categories VALUES (26, 'Для автомобилей', 25);
INSERT INTO test_categories VALUES (27, 'Для грузовиков', 25);
INSERT INTO test_categories VALUES (28, 'Для лодок', 25);